/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: AVR Creative (https://sketchfab.com/avrcreative)
license: SKETCHFAB Editorial (https://sketchfab.com/licenses)
source: https://sketchfab.com/3d-models/expedition-mecha-action-3a8d817d5bbc4a8895f1643b62bee101
title: Expedition Mecha Action
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/models/mech.glb");
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    if (!actions) {
      return;
    }

    actions.Action.play();
  }, [actions]);

  useEffect(() => {
    const playHandler = (e) => {
      if (e.key === "p") {
        actions.Action.isRunning()
          ? actions.Action.stop()
          : actions.Action.play();
      }
    };

    document.addEventListener("keydown", playHandler);

    return () => {
      document.removeEventListener("keydown", playHandler);
    };
  }, [actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <group>
              <group>
                <group>
                  <primitive object={nodes._rootJoint} />
                  <group position={[0, -3.44, 0]} />
                  <group position={[0, -3.44, 0]} />
                  <group position={[0, -3.44, 0]} />
                  <group position={[0, -3.44, 0]} />
                  <group position={[0, -3.44, 0]} />
                  <group position={[0, -3.44, 0]} />
                  <group position={[0, -3.44, 0]} />
                  <group position={[0, -3.44, 0]} />
                  <group position={[0, -3.44, 0]} />
                  <group position={[0, -3.44, 0]} />
                  <group position={[0, -3.44, 0]} />
                  <group position={[0, -3.44, 0]} />
                  <group position={[0, -3.44, 0]} />
                  <group position={[0, -3.44, 0]} />
                  <group position={[0, -3.44, 0]} />
                  <group position={[0, -3.44, 0]} />
                  <group position={[0, -3.44, 0]} />
                  <group position={[0, -3.44, 0]} />
                  <group position={[0, -3.44, 0]} />
                  <group position={[0, -3.44, 0]} />
                  <group position={[0, -3.44, 0]} />
                  <group position={[0, -3.44, 0]} />
                  <group position={[0, -3.44, 0]} />
                  <group position={[0, -3.44, 0]} />
                  <group position={[0, -3.44, 0]} />
                  <group position={[0, -3.44, 0]} />
                  <group position={[0, -3.44, 0]} />
                  <group position={[0, -3.44, 0]} />
                  <group position={[0, -3.44, 0]} />
                  <group position={[0, -3.44, 0]} />
                  <group position={[0, -3.44, 0]} />
                  <group position={[0, -3.44, 0]} />
                  <group position={[0, -3.44, 0]} />
                  <group position={[0, -3.44, 0]} />
                  <group position={[0, -3.44, 0]} />
                  <group position={[0, -3.44, 0]} />
                  <group position={[0, -3.44, 0]} />
                  <group position={[0, -3.44, 0]} />
                  <group position={[0, -3.44, 0]} />
                  <group position={[0, -3.44, 0]} />
                  <group position={[0, -3.44, 0]} />
                  <group position={[0, -3.44, 0]} />
                  <group position={[0, -3.44, 0]} />
                  <group position={[0, -3.44, 0]} />
                  <group>
                    <group position={[0, -3.44, 0]} />
                    <group position={[0, -3.44, 0]} />
                    <group position={[0, -3.44, 0]} />
                    <group position={[0, -3.44, 0]} />
                    <group position={[0, -3.44, 0]} />
                    <group position={[0, -3.44, 0]} />
                    <group position={[0, -3.44, 0]} />
                    <group position={[0, -3.44, 0]} />
                    <group position={[0, -3.44, 0]} />
                    <group position={[0, -3.44, 0]} />
                    <group position={[0, -3.44, 0]} />
                    <group position={[0, -3.44, 0]} />
                    <group position={[0, -3.44, 0]} />
                    <group position={[0, -3.44, 0]} />
                    <group position={[0, -3.44, 0]} />
                    <group position={[0, -3.44, 0]} />
                    <group position={[0, -3.44, 0]} />
                    <group position={[0, -3.44, 0]} />
                    <group position={[0, -3.44, 0]} />
                    <group position={[0, -3.44, 0]} />
                    <group position={[0, -3.44, 0]} />
                    <group position={[0, -3.44, 0]} />
                    <group position={[0, -3.44, 0]} />
                    <group position={[0, -3.44, 0]} />
                    <group position={[0, -3.44, 0]} />
                    <group position={[0, -3.44, 0]} />
                    <group position={[0, -3.44, 0]} />
                    <group position={[0, -3.44, 0]} />
                    <group position={[0, -3.44, 0]} />
                    <group position={[0, -3.44, 0]} />
                    <group position={[0, -3.44, 0]} />
                    <group position={[0, -3.44, 0]} />
                    <group position={[0, -3.44, 0]} />
                    <group position={[0, -3.44, 0]} />
                    <group position={[0, -3.44, 0]} />
                    <group position={[0, -3.44, 0]} />
                    <group position={[0, -3.44, 0]} />
                    <group position={[0, -3.44, 0]} />
                    <group position={[0, -3.44, 0]} />
                    <group position={[0, -3.44, 0]} />
                    <group position={[0, -3.44, 0]} />
                    <group position={[0, -3.44, 0]} />
                    <group position={[0, -3.44, 0]} />
                    <group position={[0, -3.44, 0]} />
                  </group>
                  <group />
                  <group scale={134.25}>
                    <mesh
                      geometry={nodes.pCircle1_floor_0.geometry}
                      material={materials.floor}
                    />
                  </group>
                  <skinnedMesh
                    geometry={nodes.Object_7.geometry}
                    material={materials.Mecha_Mat}
                    skeleton={nodes.Object_7.skeleton}
                  />
                  <skinnedMesh
                    geometry={nodes.Object_9.geometry}
                    material={materials.Mecha_Mat}
                    skeleton={nodes.Object_9.skeleton}
                  />
                  <skinnedMesh
                    geometry={nodes.Object_11.geometry}
                    material={materials.Mecha_Mat}
                    skeleton={nodes.Object_11.skeleton}
                  />
                  <skinnedMesh
                    geometry={nodes.Object_13.geometry}
                    material={materials.Mecha_Mat}
                    skeleton={nodes.Object_13.skeleton}
                  />
                  <skinnedMesh
                    geometry={nodes.Object_15.geometry}
                    material={materials.Mecha_Mat}
                    skeleton={nodes.Object_15.skeleton}
                  />
                  <skinnedMesh
                    geometry={nodes.Object_17.geometry}
                    material={materials.Mecha_Mat}
                    skeleton={nodes.Object_17.skeleton}
                  />
                  <skinnedMesh
                    geometry={nodes.Object_19.geometry}
                    material={materials.Mecha_Mat}
                    skeleton={nodes.Object_19.skeleton}
                  />
                  <skinnedMesh
                    geometry={nodes.Object_21.geometry}
                    material={materials.Mecha_Mat}
                    skeleton={nodes.Object_21.skeleton}
                  />
                  <skinnedMesh
                    geometry={nodes.Object_23.geometry}
                    material={materials.Mecha_Mat}
                    skeleton={nodes.Object_23.skeleton}
                  />
                  <skinnedMesh
                    geometry={nodes.Object_25.geometry}
                    material={materials.Mecha_Mat}
                    skeleton={nodes.Object_25.skeleton}
                  />
                  <skinnedMesh
                    geometry={nodes.Object_27.geometry}
                    material={materials.Mecha_Mat}
                    skeleton={nodes.Object_27.skeleton}
                  />
                  <skinnedMesh
                    geometry={nodes.Object_29.geometry}
                    material={materials.Mecha_Mat}
                    skeleton={nodes.Object_29.skeleton}
                  />
                  <skinnedMesh
                    geometry={nodes.Object_31.geometry}
                    material={materials.Mecha_Mat}
                    skeleton={nodes.Object_31.skeleton}
                  />
                  <skinnedMesh
                    geometry={nodes.Object_33.geometry}
                    material={materials.Mecha_Mat}
                    skeleton={nodes.Object_33.skeleton}
                  />
                  <skinnedMesh
                    geometry={nodes.Object_35.geometry}
                    material={materials.Mecha_Mat}
                    skeleton={nodes.Object_35.skeleton}
                  />
                  <skinnedMesh
                    geometry={nodes.Object_37.geometry}
                    material={materials.Mecha_Mat}
                    skeleton={nodes.Object_37.skeleton}
                  />
                  <skinnedMesh
                    geometry={nodes.Object_39.geometry}
                    material={materials.Mecha_Mat}
                    skeleton={nodes.Object_39.skeleton}
                  />
                  <skinnedMesh
                    geometry={nodes.Object_41.geometry}
                    material={materials.Mecha_Mat}
                    skeleton={nodes.Object_41.skeleton}
                  />
                  <skinnedMesh
                    geometry={nodes.Object_43.geometry}
                    material={materials.Mecha_Mat}
                    skeleton={nodes.Object_43.skeleton}
                  />
                  <skinnedMesh
                    geometry={nodes.Object_45.geometry}
                    material={materials.Mecha_Mat}
                    skeleton={nodes.Object_45.skeleton}
                  />
                  <skinnedMesh
                    geometry={nodes.Object_47.geometry}
                    material={materials.Mecha_Mat}
                    skeleton={nodes.Object_47.skeleton}
                  />
                  <skinnedMesh
                    geometry={nodes.Object_49.geometry}
                    material={materials.Mecha_Mat}
                    skeleton={nodes.Object_49.skeleton}
                  />
                  <skinnedMesh
                    geometry={nodes.Object_51.geometry}
                    material={materials.Mecha_Mat}
                    skeleton={nodes.Object_51.skeleton}
                  />
                  <skinnedMesh
                    geometry={nodes.Object_53.geometry}
                    material={materials.Mecha_Mat}
                    skeleton={nodes.Object_53.skeleton}
                  />
                  <skinnedMesh
                    geometry={nodes.Object_55.geometry}
                    material={materials.Mecha_Mat}
                    skeleton={nodes.Object_55.skeleton}
                  />
                  <skinnedMesh
                    geometry={nodes.Object_57.geometry}
                    material={materials.Mecha_Mat}
                    skeleton={nodes.Object_57.skeleton}
                  />
                  <skinnedMesh
                    geometry={nodes.Object_59.geometry}
                    material={materials.Mecha_Mat}
                    skeleton={nodes.Object_59.skeleton}
                  />
                  <skinnedMesh
                    geometry={nodes.Object_61.geometry}
                    material={materials.Mecha_Mat}
                    skeleton={nodes.Object_61.skeleton}
                  />
                  <skinnedMesh
                    geometry={nodes.Object_63.geometry}
                    material={materials.Mecha_Mat}
                    skeleton={nodes.Object_63.skeleton}
                  />
                  <skinnedMesh
                    geometry={nodes.Object_65.geometry}
                    material={materials.Mecha_Mat}
                    skeleton={nodes.Object_65.skeleton}
                  />
                  <skinnedMesh
                    geometry={nodes.Object_67.geometry}
                    material={materials.Mecha_Mat}
                    skeleton={nodes.Object_67.skeleton}
                  />
                  <skinnedMesh
                    geometry={nodes.Object_69.geometry}
                    material={materials.Mecha_Mat}
                    skeleton={nodes.Object_69.skeleton}
                  />
                  <skinnedMesh
                    geometry={nodes.Object_71.geometry}
                    material={materials.Mecha_Mat}
                    skeleton={nodes.Object_71.skeleton}
                  />
                  <skinnedMesh
                    geometry={nodes.Object_73.geometry}
                    material={materials.Mecha_Mat}
                    skeleton={nodes.Object_73.skeleton}
                  />
                  <skinnedMesh
                    geometry={nodes.Object_75.geometry}
                    material={materials.Mecha_Mat}
                    skeleton={nodes.Object_75.skeleton}
                  />
                  <skinnedMesh
                    geometry={nodes.Object_77.geometry}
                    material={materials.Mecha_Mat}
                    skeleton={nodes.Object_77.skeleton}
                  />
                  <skinnedMesh
                    geometry={nodes.Object_79.geometry}
                    material={materials.Mecha_Mat}
                    skeleton={nodes.Object_79.skeleton}
                  />
                  <skinnedMesh
                    geometry={nodes.Object_81.geometry}
                    material={materials.Mecha_Mat}
                    skeleton={nodes.Object_81.skeleton}
                  />
                  <skinnedMesh
                    geometry={nodes.Object_83.geometry}
                    material={materials.Mecha_Mat}
                    skeleton={nodes.Object_83.skeleton}
                  />
                  <skinnedMesh
                    geometry={nodes.Object_85.geometry}
                    material={materials.Mecha_Mat}
                    skeleton={nodes.Object_85.skeleton}
                  />
                  <skinnedMesh
                    geometry={nodes.Object_87.geometry}
                    material={materials.Mecha_Mat}
                    skeleton={nodes.Object_87.skeleton}
                  />
                  <skinnedMesh
                    geometry={nodes.Object_89.geometry}
                    material={materials.Mecha_Mat}
                    skeleton={nodes.Object_89.skeleton}
                  />
                  <skinnedMesh
                    geometry={nodes.Object_91.geometry}
                    material={materials.Mecha_Mat}
                    skeleton={nodes.Object_91.skeleton}
                  />
                  <skinnedMesh
                    geometry={nodes.Object_93.geometry}
                    material={materials.Mecha_Mat}
                    skeleton={nodes.Object_93.skeleton}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/mech.glb");
